name: Release Omnistrate CLI Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download release assets
        uses: robinraju/release-downloader@v1.10
        with:
          tag: ${{ github.ref }}
          out-file-path: assets
          extract: true

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/omnistrate-cli:latest,${{ secrets.DOCKER_USERNAME }}/omnistrate-cli:${{ github.ref_name }}
